version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8001"
      - "5555:5555" 
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock # Add this line to mount the Docker socket



volumes:
  db:
    driver: local
