version: "3.8"
services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  db:
    driver: local
